services:
    configuration_panel.admin:
        class: KunicMarko\SonataConfigurationPanelBundle\Admin\ConfigurationAdmin
        arguments: [~, KunicMarko\SonataConfigurationPanelBundle\Entity\AbstractConfiguration, ConfigurationPanelBundle:ConfigurationAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Configuration Panel", on_top: true , label_catalogue: ~, icon: '<i class="fa fa-sliders"></i>'}
        calls:
            - [ setAdditionalTypes, [ "%configuration_panel.types%" ] ]
            - [ setSubClasses, [{date : 'KunicMarko\SonataConfigurationPanelBundle\Entity\ConfigurationTypes\DateType', boolean : 'KunicMarko\SonataConfigurationPanelBundle\Entity\ConfigurationTypes\BooleanType', text: 'KunicMarko\SonataConfigurationPanelBundle\Entity\ConfigurationTypes\TextType', other: 'KunicMarko\SonataConfigurationPanelBundle\Entity\ConfigurationTypes\TextareaType'}]]
            - [ setAuthorizationChecker, ["@security.authorization_checker"]]
            - [ setCacheWarmer, [ "@configuration_panel.cache.warmer" ] ]

    configuration_panel.global.service:
        class: KunicMarko\SonataConfigurationPanelBundle\Services\ConfigurationService
        arguments: ["%kernel.cache_dir%"]

    # Cache
    configuration_panel.cache.warmer:
        class: KunicMarko\SonataConfigurationPanelBundle\Cache\Warmer\ConfigurationCacheWarmer
        arguments: ["@doctrine.orm.entity_manager","%kernel.cache_dir%"]
        tags:
            - { name: kernel.cache_warmer }

    configuration_panel.discriminator_map.listener:
        class: KunicMarko\SonataConfigurationPanelBundle\EventListener\DiscriminatorMapListener
        arguments: ["%configuration_panel.types%"]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    configuration_panel.twig.extension:
        class: KunicMarko\SonataConfigurationPanelBundle\Twig\GlobalVariables
        arguments: ["@configuration_panel.global.service"]
        tags:
            - { name: twig.extension }
    configuration_panel.elapsed_time.filter:
        class: KunicMarko\SonataConfigurationPanelBundle\Twig\ElapsedTime
        public: false
        tags:
            - { name: twig.extension }
